//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CertReqClient {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CertReqClient.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MessageBox.Show(messages.certificateFileNotCreated. ähnelt.
        /// </summary>
        internal static string certificateFileNotCreated {
            get {
                return ResourceManager.GetString("certificateFileNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The following Characters are not allowed: {0} ähnelt.
        /// </summary>
        internal static string charactersNotAllowed {
            get {
                return ResourceManager.GetString("charactersNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die close edit mode ähnelt.
        /// </summary>
        internal static string closeEditMode {
            get {
                return ResourceManager.GetString("closeEditMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You can now create the private key by clicking the \&quot;create private key\&quot; Button. ähnelt.
        /// </summary>
        internal static string crtPrivateKey {
            get {
                return ResourceManager.GetString("crtPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File has been successfully created!\r Do you want to create the private key now? ähnelt.
        /// </summary>
        internal static string csrCreated {
            get {
                return ResourceManager.GetString("csrCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die dns= ähnelt.
        /// </summary>
        internal static string dnsEquals {
            get {
                return ResourceManager.GetString("dnsEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DNS-Name ähnelt.
        /// </summary>
        internal static string dnsName {
            get {
                return ResourceManager.GetString("dnsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die edit SAN ähnelt.
        /// </summary>
        internal static string editSan {
            get {
                return ResourceManager.GetString("editSan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please enter the Domain. ähnelt.
        /// </summary>
        internal static string enterDomain {
            get {
                return ResourceManager.GetString("enterDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The private key file has been successfully created!\r Do you want to install the certificate now? ähnelt.
        /// </summary>
        internal static string installCertificate {
            get {
                return ResourceManager.GetString("installCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP-Address ähnelt.
        /// </summary>
        internal static string ipAddress {
            get {
                return ResourceManager.GetString("ipAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ipaddress= ähnelt.
        /// </summary>
        internal static string ipaddressEquals {
            get {
                return ResourceManager.GetString("ipaddressEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Subject Alernative Name or SAN Type is missing. ähnelt.
        /// </summary>
        internal static string missingSAN {
            get {
                return ResourceManager.GetString("missingSAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your file has been successfully created. You can now choose the right certificate
        ///request file (csr) to generate the private key. ähnelt.
        /// </summary>
        internal static string privateKeyMessage {
            get {
                return ResourceManager.GetString("privateKeyMessage", resourceCulture);
            }
        }
    }
}
